source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'QwikHttp_Example', :exclusive => true do
  pod 'QwikHttp', :path => '../'
end

target 'QwikHttp_Tests', :exclusive => true do
  pod 'QwikHttp', :path => '../'

  
end
